name: CI/CD Pipeline              # The name of the workflow

on:
  push:                           # Trigger on push to main
    branches: [main]
  pull_request:                   # Trigger on PR to main
    branches: [main]

jobs:
  build:                          # One job: "build"
    runs-on: ubuntu-latest        # Use Linux (not Windows)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Pull your repo code

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Use Python 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ tests/      # Lint source code and tests

      - name: Run unit tests
        run: |
          python -m unittest discover tests
